---
abstract: 'Serializes and deserializes Path::Class objects as file:// URI'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Path-Class-URI
no_index:
  directory:
    - inc
    - t
requires:
  Exporter::Lite: 0
  Path::Class: 0
  Scalar::Util: 0
  URI: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
